In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
data = pd.read_csv('gdp_data.csv')
data.head()

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, euro per capita",Gross domestic product at market prices,Albania,2015,3590.0,NaN,NaN
1,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, euro per capita",Gross domestic product at market prices,Albania,2016,3770.0,NaN,NaN
2,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, euro per capita",Gross domestic product at market prices,Albania,2017,4100.0,NaN,NaN
3,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, euro per capita",Gross domestic product at market prices,Albania,2018,4540.0,NaN,NaN
4,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, euro per capita",Gross domestic product at market prices,Albania,2019,4880.0,NaN,NaN

In [39]:
print(data['unit'].unique())

['Current prices, euro per capita'
 'Current prices, units of national currency per capita'
 'Current prices, purchasing power standard (PPS, EU27 from 2020) per capita']

In [40]:
polska_pps = data[(data['geo'] == 'Poland') & (data['unit'] == 'Current prices, purchasing power standard (PPS, EU27 from 2020) per capita')]
polska_pps

,DATAFLOW,LAST UPDATE,freq,unit,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
1130,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2015,19407.6,NaN,NaN
1131,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2016,19707.1,NaN,NaN
1132,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2017,20729.9,NaN,NaN
1133,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2018,21942.4,NaN,NaN
1134,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2019,23345.3,NaN,NaN
1135,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2020,23914.3,b,NaN
1136,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2021,26195.3,NaN,NaN
1137,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2022,28149.4,b,NaN
1138,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2023,29572.1,NaN,NaN
1139,ESTAT:NAMA_10_PC(1.0),05/12/25 23:00:00,Annual,"Current prices, purchasing power standard (PPS...",Gross domestic product at market prices,Poland,2024,31439.0,NaN,NaN

In [41]:
wyniki = polska_pps[['TIME_PERIOD', 'OBS_VALUE']].sort_values('TIME_PERIOD')
print(wyniki)

      TIME_PERIOD  OBS_VALUE
1130         2015    19407.6
1131         2016    19707.1
1132         2017    20729.9
1133         2018    21942.4
1134         2019    23345.3
1135         2020    23914.3
1136         2021    26195.3
1137         2022    28149.4
1138         2023    29572.1
1139         2024    31439.0